"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class strain(object):
    __slots__ = ["timestamp", "strain_value", "strain_string"]

    def __init__(self):
        self.timestamp = 0.0
        self.strain_value = 0.0
        self.strain_string = ""

    def encode(self):
        buf = BytesIO()
        buf.write(strain._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">df", self.timestamp, self.strain_value))
        __strain_string_encoded = self.strain_string.encode('utf-8')
        buf.write(struct.pack('>I', len(__strain_string_encoded)+1))
        buf.write(__strain_string_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != strain._get_packed_fingerprint():
            raise ValueError("Decode error")
        return strain._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = strain()
        self.timestamp, self.strain_value = struct.unpack(">df", buf.read(12))
        __strain_string_len = struct.unpack('>I', buf.read(4))[0]
        self.strain_string = buf.read(__strain_string_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if strain in parents: return 0
        tmphash = (0x717632eda1b5e169) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if strain._packed_fingerprint is None:
            strain._packed_fingerprint = struct.pack(">Q", strain._get_hash_recursive([]))
        return strain._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

