# Physical specification of the vehicle. 

[[asv]]
id = "asv0"
L_wl = 0.3 # m
B_wl = 0.3 # m
D = 0.3  # m
T = 0.1 # m
displacement = 0.007 # m3
max_speed = 2.0 # m/s
cog = [0.15, 0.0, -0.2] # [x(m), y(m), z(m)]
radius_of_gyration = [0.08, 0.08, 0.106] # [r_roll(m), r_pitch(m), r_yaw(m)]
# NOTE: If using the PID controller, then there must be exactly 4 thrusters which 
# must be entered in the following order = [fore_PS, fore_SB, aft_PS, aft_SB].
thrusters = [[0.235, -0.085, -0.0485],
			 [0.235, 0.085, -0.0485],
			 [0.065, -0.085, -0.0485],
			 [0.065, 0.085, -0.0485]] # [[x(m), y(m), z(m)]]
asv_position = [1000.0, 1000.0] # [X(m), Y(m)] or [X(latitude), Y(longitude)] if EARTH_COORDINATES is enabled at build time.
asv_attitude = [0.0, 0.0, 0.0] #[heel(deg), trim(deg), heading(deg)]
waypoints = [[1000.0, 1100.0], [1100.0, 1100.0]] # [[X(m), Y(m)]] or [X(latitude), Y(longitude)] if EARTH_COORDINATES is enabled at build time.

[clock]
time_step_size = 40 # milli-sec

[visualisation]
sea_surface_edge_length = 10.0 #m
sea_surface_position = [1000.0, 1000.0] # Position of the bottom-left corner of the simulated surface.
count_mesh_cells_along_edge = 10 # Number of mesh cells along one edge of the sea surface. A larger number means a finer sea surface mesh.

[cyclone]
hs_nc = ["hs1.nc", "hs2.nc", "hs2.nc"] # List of netCDF files for wave heights listed in chronological order. 
dp_nc = ["dp1.nc", "dp2.nc", "dp3.nc"] # List of netCDF files for wave heading listed in chronological order.