
COUNT_WAVE_SPECTRAL_FREQUENCIES = 15
COUNT_WAVE_SPECTRAL_DIRECTIONS  = 5 
COUNT_ASV_SPECTRAL_DIRECTIONS   = 360 
COUNT_ASV_SPECTRAL_FREQUENCIES  = 100 
COUNT_PROPELLERS_MAX            = 4 
COUNT_WAYPOINTS_MAX             = 20 
OUTPUT_BUFFER_SIZE              = 20000 