"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class joystick(object):
    __slots__ = ["timestamp", "axis_value", "joystick_string"]

    def __init__(self):
        self.timestamp = 0.0
        self.axis_value = [ 0.0 for dim0 in range(6) ]
        self.joystick_string = ""

    def encode(self):
        buf = BytesIO()
        buf.write(joystick._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">d", self.timestamp))
        buf.write(struct.pack('>6f', *self.axis_value[:6]))
        __joystick_string_encoded = self.joystick_string.encode('utf-8')
        buf.write(struct.pack('>I', len(__joystick_string_encoded)+1))
        buf.write(__joystick_string_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != joystick._get_packed_fingerprint():
            raise ValueError("Decode error")
        return joystick._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = joystick()
        self.timestamp = struct.unpack(">d", buf.read(8))[0]
        self.axis_value = struct.unpack('>6f', buf.read(24))
        __joystick_string_len = struct.unpack('>I', buf.read(4))[0]
        self.joystick_string = buf.read(__joystick_string_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if joystick in parents: return 0
        tmphash = (0x63480f0687066b70) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if joystick._packed_fingerprint is None:
            joystick._packed_fingerprint = struct.pack(">Q", joystick._get_hash_recursive([]))
        return joystick._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

